modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/Fourmisain/AxesAreWeapons/issues"

[[mods]]
modId="axesareweapons"
version="${mod_version}"
displayName="Axes Are Weapons"
displayURL="https://www.curseforge.com/minecraft/mc-mods/axes-are-weapons"
logoFile= "icon.png"
authors="Fourmisain"
description='''
Disables the increased durability loss in combat and enables Looting for axes
Damage enchantments for axes will appear in the Enchanting Table too
Check the config for more options!
'''
displayTest="IGNORE_SERVER_VERSION"

[[dependencies.axesareweapons]]
modId="neoforge"
mandatory=true
versionRange="[20.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.axesareweapons]]
modId="minecraft"
mandatory=true
versionRange="${forge_game_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.axesareweapons]]
modId="cloth_config"
mandatory=true
versionRange="[12,)"
ordering="NONE"
side="BOTH"

[[mixins]]
config = "axesareweapons.common.mixins.json"
